# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

# Comment the next line if you don't want to use dynamic frameworks
use_frameworks!

inhibit_all_warnings!

workspace 'App.xcworkspace'
project 'App.xcodeproj'

def factory_path(name)
  return "../Factory/#{name}/#{name}"
end

def foundation_path(name)
  return "../Foundations/#{name}/#{name}"
end

def common_path(name)
  return "../Commons/#{name}/#{name}"
end

def feature_path(name)
  return "../Features/#{name}/#{name}"
end

def di_pods
  pod 'Swinject', '2.9.1'
end

def core_pods
  di_pods
  pod 'PromiseKit', '6.18.0'
end

def crypto_pods
  pod 'Sodium', '0.8.0'
end

def datastore_pods
  pod 'SecureStorageSwift', '1.0.4'
end

def default_pods
  core_pods
  pod 'Moya', '15.0.0'
end

target 'App' do

  # Pods for App
  default_pods
  crypto_pods
  datastore_pods

  target 'AppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AppUITests' do
    # Pods for testing
  end

end

# Factory
target 'MDFactory' do
  project factory_path("MDFactory")
  # Pods for App
  default_pods
  crypto_pods
  
  target 'MDFactoryTests' do
    project factory_path("MDFactory")
    # Pods for testing
  end
end

# Foundations
target 'MDComponent' do
  project foundation_path("MDComponent")
  # Pods for App
  
  target 'MDComponentTests' do
    project foundation_path("MDComponent")
    # Pods for testing
  end
end

target 'MDCore' do
  project foundation_path("MDCore")
  # Pods for App
  core_pods
  
  target 'MDCoreTests' do
    project foundation_path("MDCore")
    # Pods for testing
  end
end

# Commons
target 'MDCrypto' do
  project common_path("MDCrypto")
  # Pods for App
  core_pods
  crypto_pods
  
  target 'MDCryptoTests' do
    project common_path("MDCrypto")
    # Pods for testing
  end
end

target 'MDDataStore' do
  project common_path("MDDataStore")
  # Pods for App
  core_pods
  datastore_pods
  
  target 'MDDataStoreTests' do
    project common_path("MDDataStore")
    # Pods for testing
  end
end

target 'MDNetwork' do
  project common_path("MDNetwork")
  # Pods for App
  default_pods
  
  target 'MDNetworkTests' do
    project common_path("MDNetwork")
    # Pods for testing
  end
end

# Features
target 'MDHome' do
  project feature_path("MDHome")
  # Pods for App
  default_pods
  
  target 'MDHomeTests' do
    project feature_path("MDHome")
    # Pods for testing
  end
end

target 'MDSetting' do
  project feature_path("MDSetting")
  # Pods for App
  default_pods
  
  target 'MDSettingTests' do
    project feature_path("MDSetting")
    # Pods for testing
  end
end

target 'MDProfile' do
  project feature_path("MDProfile")
  # Pods for App
  default_pods
  
  target 'MDProfileTests' do
    project feature_path("MDProfile")
    # Pods for testing
  end
end


# Post install setting
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
      config.build_settings['ONLY_ACTIVE_ARCH'] = 'YES'
      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
      config.build_settings['ENABLE_USER_SCRIPT_SANDBOXING'] = 'NO'
      config.build_settings['OTHER_SWIFT_FLAGS'] = '-no-verify-emitted-module-interface'
      #config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'NO'
    end
  end
end
